// ==========================================
// AUTO-GENERATED BY LISP ARCHITECT
// DO NOT EDIT MANUALLY - GEOMETRY IS STRICT
// ==========================================

#define EXACT_ARENA_SIZE 204
#define MAX_MSGS 5
#define MAX_MSG_LEN 32
#define MAX_DATA 16
