;; emit5.lisp
;; Bakes the C Header, Config Header, Text Arena, Numeric Arena, and Sentinel.

(defconstant +magic-number+ #x5A45524F) ; "ZERO"
(defconstant +version+ 5)

;; The Physical Configuration (The DNA)
(defconstant +msg-count+ 5)
(defconstant +msg-len+ 32)
(defconstant +data-count+ 16)
(defconstant +sentinel+ #xDEADBEEF)

;; Calculate the exact physical size of the universe
;; 24 (Config Header) + Text Arena + Numeric Arena + 4 (Sentinel)
(defconstant +total-size+ (+ 24 (* +msg-count+ +msg-len+) +data-count+ 4))

;; =========================================================================
;; C-HEADER GENERATOR PASS
;; =========================================================================
(defun bake-c-header (filename size)
  (format t "[Architect] Generating C-Header '~A' with EXACT_ARENA_SIZE ~A bytes.~%" filename size)
  (with-open-file (out filename :direction :output :if-exists :supersede)
    (format out "// ==========================================~%")
    (format out "// AUTO-GENERATED BY LISP ARCHITECT~%")
    (format out "// DO NOT EDIT MANUALLY - GEOMETRY IS STRICT~%")
    (format out "// ==========================================~%~%")
    (format out "#define EXACT_ARENA_SIZE ~A~%" size)
    (format out "#define MAX_MSGS ~A~%" +msg-count+)
    (format out "#define MAX_MSG_LEN ~A~%" +msg-len+)
    (format out "#define MAX_DATA ~A~%" +data-count+)))

;; =========================================================================
;; STATIC ANALYZER PASS
;; =========================================================================
(defun verify-geometry (messages active-index)
  (format t "[Analyzer] Verifying v~A geometry and limits...~%" +version+)
  (when (/= (length messages) +msg-count+)
    (error "[FATAL] Geometry mismatch. Expected ~A messages." +msg-count+))
  (when (or (< active-index 0) (>= active-index +msg-count+))
    (error "[FATAL] Active index ~A violates boundary limits." active-index))
  (loop for msg in messages for i from 0 do
        (when (>= (length msg) +msg-len+)
          (error "[FATAL] Message ~A overflows ~A-byte boundary." i +msg-len+)))
  (format t "[Analyzer] Geometry verified. DNA limits mapped.~%"))

;; =========================================================================
;; THE BAKE
;; =========================================================================
(defun write-uint32 (val stream)
  (write-byte (ldb (byte 8 0)  val) stream)
  (write-byte (ldb (byte 8 8)  val) stream)
  (write-byte (ldb (byte 8 16) val) stream)
  (write-byte (ldb (byte 8 24) val) stream))

(defun bake-universe (filename messages active-index)
  (verify-geometry messages active-index)
  
  (with-open-file (out filename :direction :output :element-type '(unsigned-byte 8) :if-exists :supersede)
    
    ;; 1. The Binary Configuration Header (24 bytes)
    (write-uint32 +magic-number+ out)
    (write-uint32 +version+ out)
    (write-uint32 +msg-count+ out)      
    (write-uint32 +msg-len+ out)        
    (write-uint32 +data-count+ out)     
    (write-uint32 active-index out)     
    
    ;; 2. Sub-Arena A: Text
    (loop for msg in messages do
          (loop for i from 0 below +msg-len+ do
                (write-byte (if (< i (length msg)) (char-code (char msg i)) 0) out)))
                
    ;; 3. Sub-Arena B: Numeric Data
    (loop for i from 0 below +data-count+ do
          (if (< i +msg-count+)
              (write-byte 0 out)     ; Status 0 = Pending
              (write-byte 255 out))) ; Status 255 = Null/Padding
                
    ;; 4. The Footer / Sentinel (4 bytes)
    (write-uint32 +sentinel+ out)))

;; =========================================================================
;; EXECUTION
;; =========================================================================
(defparameter *task-phases*
  '("Phase 1: Boot sequence"
    "Phase 2: Establish uplink"
    "Phase 3: Synchronize data"
    "Phase 4: Deploy payload"
    "Phase 5: Terminate"))

(bake-c-header "arena_spec.h" +total-size+)
(bake-universe "world5.bin" *task-phases* 0)
(format t "[Lisp] Single Source of Truth compiled. Binary: 'world5.bin' (v~A).~%" +version+)
(sb-ext:exit)