// main5.c
#include <stdio.h>
#include <stdint.h>
#include <string.h>

// Bring in the strict limits generated by the Lisp Architect
#include "arena_spec.h" 

// =========================================================================
// THE PHYSICAL SPEC v5
// The struct geometry must perfectly match EXACT_ARENA_SIZE.
// =========================================================================
typedef struct {
    uint32_t magic;
    uint32_t version;
    uint32_t msg_count;         
    uint32_t msg_len;           
    uint32_t data_count;        
    uint32_t active_index;      
} BinaryConfig;

typedef struct {
    BinaryConfig config;                                
    char         messages[MAX_MSGS][MAX_MSG_LEN]; 
    uint8_t      statuses[MAX_DATA];            
    uint32_t     sentinel;                      
} ExecutionState;

// Compile-time geometry enforcement
_Static_assert(sizeof(ExecutionState) == EXACT_ARENA_SIZE,
               "ExecutionState layout mismatch: padding or alignment error.");

int main() {
    // 1. EXACT ALLOCATION (Zero Dead Memory)
    // We allocate exactly what Lisp told the compiler we needed.
    uint8_t arena[EXACT_ARENA_SIZE]; 
    
    // 2. FILE WEIGHT VERIFICATION
    FILE *f = fopen("world5.bin", "rb");
    if (!f) {
        printf("[FATAL] Could not find 'world5.bin'.\n");
        return 1;
    }
    
    // Check the exact file size on disk before loading
    fseek(f, 0, SEEK_END);
    long file_size = ftell(f);
    fseek(f, 0, SEEK_SET); // Rewind back to start
    
    if (file_size != EXACT_ARENA_SIZE) {
        printf("[FATAL] File weight mismatch! Expected %d bytes, got %ld bytes on disk.\n", EXACT_ARENA_SIZE, file_size);
        fclose(f);
        return 1;
    }

    // 3. ZERO-OVERHEAD HYDRATION
    fread(arena, 1, EXACT_ARENA_SIZE, f);
    fclose(f);

    ExecutionState *state = (ExecutionState*)arena;

    // 4. GEOMETRIC & DNA VERIFICATION
    if (state->config.magic != 0x5A45524F || state->config.version != 5 || state->sentinel != 0xDEADBEEF) {
        printf("[FATAL] Geometry or DNA Header Mismatch!\n");
        return 1;
    }

    // 5. EXECUTION STATE CHECK
    uint32_t idx = state->config.active_index;
    
    if (idx >= state->config.msg_count) {
        printf("\n--- HYDRATION SUCCESS (v%u | EXACT MEMORY: %d bytes) ---\n", state->config.version, EXACT_ARENA_SIZE);
        printf("[C Runtime] ALL TASKS COMPLETE. Halting sequence.\n");
        return 0;
    }

    printf("\n--- HYDRATION SUCCESS (v%u | EXACT MEMORY: %d bytes) ---\n", state->config.version, EXACT_ARENA_SIZE);
    printf("Limits Loaded: %u Messages, %u Numeric Slots\n", state->config.msg_count, state->config.data_count);
    
    char* active_task = state->messages[idx];
    uint8_t active_status = state->statuses[idx];
    
    printf(">>> CURRENT TASK [%u]: %s (Status Code: %u)\n", idx, active_task, active_status);

    // 6. MUTATION
    printf("[C Runtime] Processing task...\n");
    strncpy(active_task, "[DONE] Task completed.", state->config.msg_len - 1);
    
    // Update the numeric sub-arena (Change Status from 0 to 1)
    state->statuses[idx] = 1; 
    state->config.active_index += 1;

    // 7. DEHYDRATION (Persist the exact arena size back to disk)
    FILE *out = fopen("world5.bin", "wb");
    fwrite(state, 1, EXACT_ARENA_SIZE, out);
    fclose(out);
    
    printf("[SUCCESS] Task marked complete (Status=1). File 'world5.bin' overwritten.\n");

    return 0;
}